[ollama]
base_url = "http://127.0.0.1:11434"
default_model = "mistral-small"

[exo]
base_url = "http://localhost:52415"
enable_cluster = false

[chat]
temperature = 0.7
max_tokens = 512
stream = true


[search]
provider = "bing"
api_key = ""  # DuckDuckGo doesn't require an API key
